# Generated by Django 5.2.8 on 2025-11-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_city_customer_country_customer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_transfer_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily transfer limit (leave empty for unlimited)', max_digits=15, null=True),
        ),
    ]
