# Generated by Django 5.2.8 on 2025-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_daily_transfer_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(blank=True, help_text='4-6 digit PIN for transactions', max_length=6, null=True),
        ),
    ]
