# Generated by Django 5.2.8 on 2025-11-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_payment_method_transaction_payment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
    ]
