# Generated by Django 5.2.8 on 2025-11-19 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('login', 'Device Login'), ('registration', 'Account Registration'), ('activation', 'Account Activation'), ('deposit', 'Deposit Transaction'), ('withdrawal', 'Withdrawal Transaction'), ('transfer_sent', 'Transfer Sent'), ('transfer_received', 'Transfer Received'), ('loan_applied', 'Loan Application'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('password_changed', 'Password Changed'), ('pin_changed', 'PIN Changed'), ('profile_updated', 'Profile Updated'), ('transaction_pending', 'Transaction Pending'), ('transaction_completed', 'Transaction Completed'), ('transaction_failed', 'Transaction Failed'), ('transaction_cancelled', 'Transaction Cancelled'), ('limit_updated', 'Transfer Limit Updated'), ('security_alert', 'Security Alert'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data related to the notification', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
